### ISSUE TITLE
RRF3 Virtual Heater for drivers

### ISSUE THREAD

**Issue by ccomincini** [gloomyandy/CoreSTM32F4#1]
Hi,
First at all, thankyou for sharing your exceptional knowledge.
I've recently removed a burned duet+ duex from my printer and mounted a Octopus Pro F429.
In my old configuration I was able to address a sensor for monitorng Drivers temp. On the duet3d and duex there is a pin number called 'drivers' or 'duex_drivers'  that you ca use to address a Sensor and monitor temp for starting a fan in case of overtemp.
I wnt to install two fans to cooldown the 7 drivers I'm using; Do you know if is it possible to do the same thing on the Octopus? 
Please accept excuses if the messahe is OOT, but I'm not able to find any suggestion over the Net and so I' writing here.

**Comment by gloomyandy** [comment]
Hi,
We prefer that users use our Discord server for support questions. See: https://teamgloomy.github.io/support.html

The quick answer is that the mechanism is exactly the same as used by the Duet3D version of RRF (assuming you are using TMC22xx or TMC5160 drivers), so you can use the "drivers" sensor. See: https://docs.duet3d.com/en/User_manual/Connecting_hardware/Temperature_configuring_mcu_temp

**Comment by ccomincini** [comment]
Thankyou. And sorry.. I'm not a discord fan ;-)
